version: '3.7'

services: 
  app:
    container_name: flask
    build: .
    env_file: database.conf
    expose: 
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
   db_volume:
